# Site settings
title: Florian Bertholin
description: 'Go/Ruby/Rails software engineer based near Geneva, Switzerland'
url: 'http://www.florianbertholinc.com'
baseurl: '/'
base_url: '/'
google_analytics: 'UA-37818424-1'
disqus_shortname: 'fbertholin'

author:
  name: 'Florian Bertholin'
  email: florian@bertholin.com
  twitter_username: fbertholin
  # facebook_username: florian.bertholin
  github_username:  arkan
  linkedin_username: fbertholin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
